image:
  file: .gitpod.Dockerfile
ports:
    - port: 3000
      onOpen: open-preview
      visibility: public
    - port: 3306
      onOpen: ignore
      visibility: public
tasks:
  - init: >
      (cp -n .env.example .env || true) && 
      pipenv install &&
      psql -U gitpod -c 'CREATE DATABASE example;' &&
      psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d example &&
      psql -c "ALTER USER gitpod PASSWORD 'postgres';" &&
      bash database.sh &&
      python docs/assets/welcome.py
    command: >
        pipenv run start;

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: false
